CREATE TABLE usuarios (
  id INTEGER NOT NULL AUTO_INCREMENT,
  email VARCHAR(45) NOT NULL UNIQUE,
  nome VARCHAR(45) NOT NULL,
  usuario VARCHAR(45) NOT NULL UNIQUE,
  senha VARCHAR(45) NOT NULL,
  CONSTRAINT pk_Usuario PRIMARY KEY(id)
);
